name: Build Mods

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    strategy:
      fail-fast: false
      matrix:
        version: [SWORD, SHIELD]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build flatc
      run: |
        cd ./include/flatbuffers/
        git fetch --unshallow
        sudo apt-get update && sudo apt-get install build-essential -y
        cmake -G "Unix Makefiles"
        make
        sudo make install
        cd ../../
    - name: Build
      run: |
        version=${{ matrix.version }} ./exlaunch.sh build
        version=${{ matrix.version }} ./exlaunch.sh deploy-artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_artifact
        path: ./artifact/
              
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Zip artifacts for release
        run: |
          for i in */; do zip -r "${i%/}.zip" "$i"; done
        working-directory: artifacts
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: Release
          tag_name: release
          body: ${{ github.event.head_commit.message }}
          files: artifacts/*
          
